# Generated by Django 2.2.10 on 2021-08-21 16:29

from django.db import migrations, models
import django.db.models.deletion
import poll_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer_type', models.IntegerField(default=poll_app.models.AnswerTypes(0))),
                ('answer_list', models.TextField()),
                ('right_answer', models.TextField()),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.Poll')),
            ],
        ),
    ]
